name = "env"
grammar = "env"
path_suffixes = ["conf", "env", "envrc", "example", "local", "dev", "Secrets.toml"]
autoclose_before = ";:.,=}])>"
line_comments = ["# "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
